version: "3"
services:
  endtoend:
    image: app
    ports:
      - "8080:8080"
    networks:
      - mynet
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    networks:
      - mynet
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - myvol:/var/lib/mysql

networks:
  mynet:
    driver: bridge
volumes:
  myvol:
    driver: local
